language: ruby

bundler_args: --without development

env:
  global:
    - "IaTyG4H1eYWG9/TxquLRqZjCdlU8SrMe6XavjW+d4KxxlkNUxdZxHnAlQ3UNlJEsH6rNBnkKhrV3OQEVvlmJ+zRs2LFeNNuNnDs/YsTpiVVtQKs3ePipAbCevDoHoL3IOyYjpBdbyaMJAJLi7rzXHhWoM1Z9nL0RbAzy393C9aw="

script: bundle exec rake travis

rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: ruby-head
  fast_finish: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adcc5723bad8796268d6
    on_success: always
    on_failure: always
    on_start: always
