language: ruby

bundler_args: --without development

script: bundle exec rake travis

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: 2.1.0
    - rvm: ruby-head
  fast_finish: true
